use tiendaxyz
----------------------------------------1-------------------------------------------------------------------------------------
alter table sucursal_sucursal1 add primary key (IDsucursal);
alter table gastos_sucursal1 add primary key (IDgastos);
alter table empleado_sucursal1 add primary key (DNI);
alter table equipo_sucursal1 add primary key (IDequipo);
alter table sucursal_equipo_S1 add primary key (IDsucursal, IDequipo);
alter table cliente_sucursal1 add primary key (DNI);
alter table sucursal_cliente_S1 add primary key (DNIcliente,IDsucursal);
alter table reserva_sucursal1 add primary key (id);
alter table factura_sucursal1 add primary key (IDfactura);
alter table factura_equipo_sucursal1 add primary key (id_factura,id_equipo);

ALTER TABLE  factura_sucursal1  ADD FOREIGN KEY (DNIempleado) REFERENCES  empleado_sucursal1  ( DNI );
ALTER TABLE  factura_sucursal1  ADD FOREIGN KEY (id_reserva) REFERENCES  reserva_sucursal1  ( id );
ALTER TABLE  factura_sucursal1  ADD FOREIGN KEY (id_sucursal) REFERENCES  sucursal_sucursal1  ( IDsucursal );
ALTER TABLE  factura_sucursal1  ADD FOREIGN KEY (id_cliente) REFERENCES  cliente_sucursal1  ( DNI );
ALTER TABLE  gastos_sucursal1  ADD FOREIGN KEY (IDsucursal) REFERENCES  sucursal_sucursal1  ( IDsucursal );
ALTER TABLE  sucursal_equipo_S1  ADD FOREIGN KEY (IDequipo) REFERENCES  equipo_sucursal1  ( IDequipo );
ALTER TABLE  empleado_sucursal1  ADD FOREIGN KEY (IDsucursal) REFERENCES  sucursal_sucursal1  ( IDsucursal );
ALTER TABLE  sucursal_equipo_S1  ADD FOREIGN KEY (IDsucursal) REFERENCES  sucursal_sucursal1  ( IDsucursal );
ALTER TABLE  sucursal_cliente_S1  ADD FOREIGN KEY (DNIcliente) REFERENCES  cliente_sucursal1  ( DNI );
ALTER TABLE  sucursal_cliente_S1  ADD FOREIGN KEY (IDsucursal) REFERENCES  sucursal_sucursal1  ( IDsucursal );
ALTER TABLE  reserva_sucursal1  ADD FOREIGN KEY (id_equipo) REFERENCES  equipo_sucursal1  ( IDequipo );
ALTER TABLE  reserva_sucursal1  ADD FOREIGN KEY (DNI_cliente) REFERENCES  cliente_sucursal1  ( DNI );
ALTER TABLE  reserva_sucursal1  ADD FOREIGN KEY (DNI_empleado) REFERENCES  empleado_sucursal1  ( DNI );
ALTER TABLE  reserva_sucursal1  ADD FOREIGN KEY (id_sucursal) REFERENCES  sucursal_sucursal1  ( IDsucursal );
ALTER TABLE  factura_equipo_sucursal1  ADD FOREIGN KEY (id_factura) REFERENCES  factura_sucursal1  ( IDfactura );
ALTER TABLE  factura_equipo_sucursal1  ADD FOREIGN KEY (id_equipo) REFERENCES  equipo_sucursal1  ( IDequipo );
--------------------------------------2-----------------------------------------------------------------------------
alter table sucursal_sucursal2 add primary key (IDsucursal);
alter table gastos_sucursal2 add primary key (IDgastos);
alter table empleado_sucursal2 add primary key (DNI);
alter table equipo_sucursal2 add primary key (IDequipo);
alter table sucursal_equipo_S2 add primary key (IDsucursal, IDequipo);
alter table cliente_sucursal2 add primary key (DNI);
alter table sucursal_cliente_S2 add primary key (DNIcliente,IDsucursal);
alter table reserva_sucursal2 add primary key (id);
alter table factura_sucursal2 add primary key (IDfactura);
alter table factura_equipo_sucursal2 add primary key (id_factura,id_equipo);

ALTER TABLE  factura_sucursal2  ADD FOREIGN KEY (DNIempleado) REFERENCES  empleado_sucursal2  ( DNI );
ALTER TABLE  factura_sucursal2  ADD FOREIGN KEY (id_reserva) REFERENCES  reserva_sucursal2  ( id );
ALTER TABLE  factura_sucursal2  ADD FOREIGN KEY (id_sucursal) REFERENCES  sucursal_sucursal2  ( IDsucursal );
ALTER TABLE  factura_sucursal2  ADD FOREIGN KEY (id_cliente) REFERENCES  cliente_sucursal2  ( DNI );
ALTER TABLE  gastos_sucursal2  ADD FOREIGN KEY (IDsucursal) REFERENCES  sucursal_sucursal2  ( IDsucursal );
ALTER TABLE  sucursal_equipo_S2  ADD FOREIGN KEY (IDequipo) REFERENCES  equipo_sucursal2  ( IDequipo );
ALTER TABLE  empleado_sucursal2  ADD FOREIGN KEY (IDsucursal) REFERENCES  sucursal_sucursal2  ( IDsucursal );
ALTER TABLE  sucursal_equipo_S2  ADD FOREIGN KEY (IDsucursal) REFERENCES  sucursal_sucursal2  ( IDsucursal );
ALTER TABLE  sucursal_cliente_S2  ADD FOREIGN KEY (DNIcliente) REFERENCES  cliente_sucursal2  ( DNI );
ALTER TABLE  sucursal_cliente_S2  ADD FOREIGN KEY (IDsucursal) REFERENCES  sucursal_sucursal2  ( IDsucursal );
ALTER TABLE  reserva_sucursal2  ADD FOREIGN KEY (id_equipo) REFERENCES  equipo_sucursal2  ( IDequipo );
ALTER TABLE  reserva_sucursal2  ADD FOREIGN KEY (DNI_cliente) REFERENCES  cliente_sucursal2  ( DNI );
ALTER TABLE  reserva_sucursal2  ADD FOREIGN KEY (DNI_empleado) REFERENCES  empleado_sucursal2  ( DNI );
ALTER TABLE  reserva_sucursal2  ADD FOREIGN KEY (id_sucursal) REFERENCES  sucursal_sucursal2  ( IDsucursal );
ALTER TABLE  factura_equipo_sucursal2  ADD FOREIGN KEY (id_factura) REFERENCES  factura_sucursal2  ( IDfactura );
ALTER TABLE  factura_equipo_sucursal2  ADD FOREIGN KEY (id_equipo) REFERENCES  equipo_sucursal2  ( IDequipo );
---------------------------------------------------------3-----------------------------------------------------------------
alter table sucursal_sucursal3 add primary key (IDsucursal);
alter table gastos_sucursal3 add primary key (IDgastos);
alter table empleado_sucursal3 add primary key (DNI);
alter table equipo_sucursal3 add primary key (IDequipo);
alter table sucursal_equipo_S3 add primary key (IDsucursal, IDequipo);
alter table cliente_sucursal3 add primary key (DNI);
alter table sucursal_cliente_S3 add primary key (DNIcliente,IDsucursal);
alter table reserva_sucursal3 add primary key (id);
alter table factura_sucursal3 add primary key (IDfactura);
alter table factura_equipo_sucursal3 add primary key (id_factura,id_equipo);

ALTER TABLE  factura_sucursal3  ADD FOREIGN KEY (DNIempleado) REFERENCES  empleado_sucursal3  ( DNI );
ALTER TABLE  factura_sucursal3  ADD FOREIGN KEY (id_reserva) REFERENCES  reserva_sucursal3  ( id );
ALTER TABLE  factura_sucursal3  ADD FOREIGN KEY (id_sucursal) REFERENCES  sucursal_sucursal3  ( IDsucursal );
ALTER TABLE  factura_sucursal3  ADD FOREIGN KEY (id_cliente) REFERENCES  cliente_sucursal3  ( DNI );
ALTER TABLE  gastos_sucursal3  ADD FOREIGN KEY (IDsucursal) REFERENCES  sucursal_sucursal3  ( IDsucursal );
ALTER TABLE  sucursal_equipo_S3  ADD FOREIGN KEY (IDequipo) REFERENCES  equipo_sucursal3  ( IDequipo );
ALTER TABLE  empleado_sucursal3  ADD FOREIGN KEY (IDsucursal) REFERENCES  sucursal_sucursal3  ( IDsucursal );
ALTER TABLE  sucursal_equipo_S3  ADD FOREIGN KEY (IDsucursal) REFERENCES  sucursal_sucursal3  ( IDsucursal );
ALTER TABLE  sucursal_cliente_S3  ADD FOREIGN KEY (DNIcliente) REFERENCES  cliente_sucursal3  ( DNI );
ALTER TABLE  sucursal_cliente_S3  ADD FOREIGN KEY (IDsucursal) REFERENCES  sucursal_sucursal3  ( IDsucursal );
ALTER TABLE  reserva_sucursal3  ADD FOREIGN KEY (id_equipo) REFERENCES  equipo_sucursal3  ( IDequipo );
ALTER TABLE  reserva_sucursal3  ADD FOREIGN KEY (DNI_cliente) REFERENCES  cliente_sucursal3  ( DNI );
ALTER TABLE  reserva_sucursal3  ADD FOREIGN KEY (DNI_empleado) REFERENCES  empleado_sucursal3  ( DNI );
ALTER TABLE  reserva_sucursal3  ADD FOREIGN KEY (id_sucursal) REFERENCES  sucursal_sucursal3  ( IDsucursal );
ALTER TABLE  factura_equipo_sucursal3  ADD FOREIGN KEY (id_factura) REFERENCES  factura_sucursal3  ( IDfactura );
ALTER TABLE  factura_equipo_sucursal3  ADD FOREIGN KEY (id_equipo) REFERENCES  equipo_sucursal3  ( IDequipo );
-----------------------------------------------------------------4----------------------------------------------------
alter table sucursal_sucursal4 add primary key (IDsucursal);
alter table gastos_sucursal4 add primary key (IDgastos);
alter table empleado_sucursal4 add primary key (DNI);
alter table equipo_sucursal4 add primary key (IDequipo);
alter table sucursal_equipo_S4 add primary key (IDsucursal, IDequipo);
alter table cliente_sucursal4 add primary key (DNI);
alter table sucursal_cliente_S4 add primary key (DNIcliente,IDsucursal);
alter table reserva_sucursal4 add primary key (id);
alter table factura_sucursal4 add primary key (IDfactura);
alter table factura_equipo_sucursal4 add primary key (id_factura,id_equipo);

ALTER TABLE  factura_sucursal4  ADD FOREIGN KEY (DNIempleado) REFERENCES  empleado_sucursal4  ( DNI );
ALTER TABLE  factura_sucursal4  ADD FOREIGN KEY (id_reserva) REFERENCES  reserva_sucursal4  ( id );
ALTER TABLE  factura_sucursal4  ADD FOREIGN KEY (id_sucursal) REFERENCES  sucursal_sucursal4  ( IDsucursal );
ALTER TABLE  factura_sucursal4  ADD FOREIGN KEY (id_cliente) REFERENCES  cliente_sucursal4  ( DNI );
ALTER TABLE  gastos_sucursal4  ADD FOREIGN KEY (IDsucursal) REFERENCES  sucursal_sucursal4  ( IDsucursal );
ALTER TABLE  sucursal_equipo_S4  ADD FOREIGN KEY (IDequipo) REFERENCES  equipo_sucursal4  ( IDequipo );
ALTER TABLE  empleado_sucursal4  ADD FOREIGN KEY (IDsucursal) REFERENCES  sucursal_sucursal4  ( IDsucursal );
ALTER TABLE  sucursal_equipo_S4  ADD FOREIGN KEY (IDsucursal) REFERENCES  sucursal_sucursal4  ( IDsucursal );
ALTER TABLE  sucursal_cliente_S4  ADD FOREIGN KEY (DNIcliente) REFERENCES  cliente_sucursal4  ( DNI );
ALTER TABLE  sucursal_cliente_S4  ADD FOREIGN KEY (IDsucursal) REFERENCES  sucursal_sucursal4  ( IDsucursal );
ALTER TABLE  reserva_sucursal4  ADD FOREIGN KEY (id_equipo) REFERENCES  equipo_sucursal4  ( IDequipo );
ALTER TABLE  reserva_sucursal4  ADD FOREIGN KEY (DNI_cliente) REFERENCES  cliente_sucursal4  ( DNI );
ALTER TABLE  reserva_sucursal4  ADD FOREIGN KEY (DNI_empleado) REFERENCES  empleado_sucursal4  ( DNI );
ALTER TABLE  reserva_sucursal4  ADD FOREIGN KEY (id_sucursal) REFERENCES  sucursal_sucursal4  ( IDsucursal );
ALTER TABLE  factura_equipo_sucursal4  ADD FOREIGN KEY (id_factura) REFERENCES  factura_sucursal4  ( IDfactura );
ALTER TABLE  factura_equipo_sucursal4  ADD FOREIGN KEY (id_equipo) REFERENCES  equipo_sucursal4  ( IDequipo );
